### ISSUE TITLE
How to disable client caching completely?

### ISSUE THREAD

**Issue by jasonadkison** [SalesforceCommerceCloud/commerce-sdk-core#31]
According to the [In Memory Cache docs for commerce-sdk](https://github.com/SalesforceCommerceCloud/commerce-sdk#in-memory-cache) it should be possible to disable caching by setting the `cacheManager` setting to `null`. This does not work as described because the `cacheManager` config property type is `ICacheManager | undefined`.

Also, the `BaseClient` class sets the default `cacheManager` config property to use `quick-lru`, so I don't see of any way for disabling the cache manager functionality completely through the config values. https://github.com/SalesforceCommerceCloud/commerce-sdk-core/blob/master/src/base/client.ts#L65 

Our use case does not require caching so I'd like to disable it completely.

**Comment by jbegleiter-sf** [comment]
Closing this issue. Please feel free to reopen along with requested info if you continue to experience this problem.
